### ISSUE TITLE
Getting "Undefined variable $name" when using a custom endpoint

### ISSUE THREAD

**Issue by andreifiroiu** [mindee/mindee-api-php#41]
The error is here:
https://github.com/mindee/mindee-api-php/blame/138749a180053b334c8ab7dfc7b7cbea0112f4b6/src/Product/Generated/GeneratedV1Document.php#L39

It's triggered when parsing a "Number" field.

A quick fix would be to replace $name with $fieldName, but I'm not sure what the purpose of this line is, so I opened an issue instead of a PR.

![image](https://github.com/mindee/mindee-api-php/assets/4728003/154f5ba6-4e25-46fa-9af2-f103a7fca3fd)

**Comment by sebastianMindee** [comment]
Hello, thank you for raising this.

We can roll out a fix pretty soon, but tests for docTI seem to not be as exhaustive as we initially thought. Do you mind sharing this "Number" field's configuration, and its read value? If it is sensitive information, just a similar example will do.

**Comment by andreifiroiu** [comment]
So the field configuration is pretty simple: 

<img width="526" alt="Screenshot 2024-03-20 at 19 37 36" src="https://github.com/mindee/mindee-api-php/assets/4728003/1af73812-bb40-4816-b5a5-c18911b1676f">

There is no problem with the actual value. My confusion was not with the cast or suffixing the value with ".0", but with the actual assignment to a property of the class instead of modifying the value in $fieldContentsStr['value'], because from what I can figure, the class property is not used anywhere else. 

So I tried 2 variations:

` $this->{$fieldName} = $fieldContentsStr['value'] . ".0"; // variant 1`

The output looks like this:
![Screenshot 2024-03-20 at 19 54 04](https://github.com/mindee/mindee-api-php/assets/4728003/2c19544b-dcb0-467e-99db-c7cfdd668410)

This is actually doing the cast to int, even if the container class is StringField, but as I had a hunch this line is not doing anything actually, I've made a test with it commented, and I got the same result, so in this form, it really does not do anything :)


For the second variation:

`$fieldContentsStr['value'] .= ".0";  // variant 2`

the output is:
![Screenshot 2024-03-20 at 19 58 56](https://github.com/mindee/mindee-api-php/assets/4728003/c5dfe2d1-1403-4294-9d13-fba3eb7fb9eb)

In this case, the value has the .0 suffix but is returned as a string, which is not quite what you'd expect for a Number field. In theory, you can apply a cast to the result, and in my case is working both ways, but I'm not sure it won't cause any problems for someone omitting the cast and getting "1325.0" instead of "1325". 

I hope this helps :)

**Comment by sebastianMindee** [comment]
I see, the ".0" suffix is due to the way we do tests for this product across all SDKS at the moment. Since we cannot guess the "format" the same way we do on other APIs, we coerce all unknowns into strings or null. For integers, we chose to add the decimal places to keep coherent with some of our other tools.

Anyhow, the fix should be live & running now.

Thank you for the very comprehensive feedback!
