### ISSUE TITLE
Composer: missing binary file in "bin" directory

### ISSUE THREAD

**Issue by Divi** [mindee/mindee-api-php#69]
### Prerequisites

Put an X between the brackets on this line if you have done all of the following:

* [X] Reproduced the problem or exposed a new need
* [X] Checked the GitHub existing issues

### Description

When doing a `composer install`, the binary `mindee` is missing in the `/bin` directory.
There is a warning message after the `composer install`

> Skipped installation of bin bin/mindee for package mindee/mindee: file not found in package

### Steps to Reproduce

* run a `composer install`

**Expected behavior:**

Creating a file `mindee` in `bin/mindee`.

**Actual behavior:**

Missing file, seems to be in the root directory.

**Reproduces how often:**

100%

### Versions

> mindee/mindee => 1.8.0

PHP 8.3.6

**Comment by sebastianMindee** [comment]
Well spotted! Will be fixed shortly.
